rm output/logs/* -f
rm output/orig/*.jpg -f
rm output/norm/*.jpg -f
rm output/corig/*.jpg -f
rm output/cnorm/*.jpg -f
rm output/training/orig/*.jpg -f
rm output/training/norm/*.jpg -f
rm output/training/corig/*.jpg -f
rm output/training/cnorm/*.jpg -f
